version: '3.9'

services:
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: protic_absensi
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network  

  sso:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/protic_absensi?schema=public
    depends_on:
      - db
    networks:
      - app_network  

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app_network  

volumes:
  db_data:

networks:
  app_network:
    driver: bridge  
